apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
   name: basic-discovery
  spec:
    ports:
    - name: discovery
      port: 10261
      protocol: TCP
      targetPort: 10261
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-grafana
  spec:
    ports:
    - name: http-grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-monitor-reloader
  spec:
    ports:
    - name: tcp-reloader
      port: 9089
      protocol: TCP
      targetPort: 9089
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
   name: basic-pd
  spec:
    ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-pd-peer
  spec:
    ports:
    - name: peer
      port: 2380
      protocol: TCP
      targetPort: 2380
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: monitor
      app.kubernetes.io/instance: basic
    name: basic-prometheus
  spec:
    ports:
    - name: http-prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app.kubernetes.io/component: monitor
      app.kubernetes.io/instance: basic
      app.kubernetes.io/name: tidb-cluster
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-tidb
  spec:
    ports:
    - name: mysql-client
      port: 4000
      protocol: TCP
      targetPort: 4000
    - name: status
      port: 10080
      protocol: TCP
      targetPort: 10080
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-tidb-peer
  spec:
    ports:
    - name: status
      port: 10080
      protocol: TCP
      targetPort: 10080
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-tikv-peer
  spec:
    ports:
    - name: peer
      port: 20160
      protocol: TCP
      targetPort: 20160
    publishNotReadyAddresses: true
    type: ClusterIP
kind: List
