apiVersion: v1
kind: Service
metadata:
  name: basic-tikv-peer
  labels:
    app: basic-tikv-peer
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: basic-tikv-peer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: basic-tikv
  labels:
    app.kubernetes.io/component: tikv
    app.kubernetes.io/instance: basic
spec:
  serviceName: "basic-tikv-peer"
  podManagementPolicy: Parallel
  replicas: 3
  selector:
     matchLabels:
       app: basic-tikv-peer
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tikv
        app.kubernetes.io/instance: basic
    spec:
      containers:
      - command:
        - /bin/sh
        - /usr/local/bin/tikv_start_script.sh
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          value: basic
        - name: HEADLESS_SERVICE_NAME
          value: basic-tikv-peer
        - name: CAPACITY
          value: "0"
        - name: TZ
          value: UTC
        image: pingcap/tikv:v3.0.13
        imagePullPolicy: IfNotPresent
        name: tikv
        ports:
        - containerPort: 20160
          name: server
          protocol: TCP
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/podinfo
          name: annotations
          readOnly: true
        - mountPath: /var/lib/tikv
          name: tikv
        - mountPath: /etc/tikv
          name: config
          readOnly: true
        - mountPath: /usr/local/bin
          name: startup-script
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: annotations
      - configMap:
          defaultMode: 420
          items:
          - key: config-file
            path: tikv.toml
          name: basic-tikv
        name: config
      - configMap:
          defaultMode: 420
          items:
          - key: startup-script
            path: tikv_start_script.sh
          name: basic-tikv
        name: startup-script
  updateStrategy:
    rollingUpdate:
      partition: 3
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: tikv
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem