apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: pd
      app.kubernetes.io/instance: basic
    name: basic-pd
  spec:
    ports:
    - name: client
      port: 2379
      protocol: TCP
      targetPort: 2379
    selector:
      app.kubernetes.io/component: pd
      app.kubernetes.io/instance: basic
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: pd
      app.kubernetes.io/instance: basic
    name: basic-pd-peer
  spec:
    ports:
      - name: peer
        port: 2380
        protocol: TCP
        targetPort: 2380
    selector:
      app.kubernetes.io/component: pd
      app.kubernetes.io/instance: basic
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-tidb
    labels:
      app.kubernetes.io/component: tidb
      app.kubernetes.io/instance: basic
  spec:
    selector:
      app.kubernetes.io/component: tidb
      app.kubernetes.io/instance: basic
    ports:
    - name: mysql-client
      port: 4000
      protocol: TCP
      targetPort: 4000
    - name: status
      port: 10080
      protocol: TCP
      targetPort: 10080
    type: ClusterIP
  #peer
- apiVersion: v1
  kind: Service
  metadata:
    name: basic-tidb-peer
    labels:
      app.kubernetes.io/component: tidb
      app.kubernetes.io/instance: basic
  spec:
    ports:
    - name: status
      port: 10080
      protocol: TCP
      targetPort: 10080
    selector:
      app.kubernetes.io/component: tidb
      app.kubernetes.io/instance: basic
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/component: tikv
      app.kubernetes.io/instance: basic
    name: basic-tikv-peer
  spec:
    ports:
    - name: peer
      port: 20160
      protocol: TCP
      targetPort: 20160
    selector:
      app.kubernetes.io/component: tikv
      app.kubernetes.io/instance: basic
    type: ClusterIP