apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: basic-pd
  labels:
        app.kubernetes.io/component: pd
        app.kubernetes.io/instance: basic
spec:
  podManagementPolicy: Parallel
  replicas: 3
  serviceName: "basic-pd-peer"
  
  selector:
    matchLabels:
      app.kubernetes.io/component: pd
      app.kubernetes.io/instance: basic
  template:
    metadata:
      labels:
        app.kubernetes.io/component: pd
        app.kubernetes.io/instance: basic
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '2379'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - command:
        - /bin/sh
        - /usr/local/bin/pd_start_script.sh
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PEER_SERVICE_NAME
          value: basic-pd-peer
        - name: SERVICE_NAME
          value: basic-pd
        - name: SET_NAME
          value: basic-pd
        - name: TZ
          value: UTC
        image: pingcap/pd:v3.0.13
        imagePullPolicy: IfNotPresent
        name: pd
        ports:
        - containerPort: 2380
          name: server
          protocol: TCP
        - containerPort: 2379
          name: client
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/podinfo
          name: annotations
          readOnly: true
        - mountPath: /etc/pd
          name: config
          readOnly: true
        - mountPath: /usr/local/bin
          name: startup-script
          readOnly: true
        - mountPath: /var/lib/pd
          name: pd
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: annotations
      - configMap:
          defaultMode: 420
          items:
          - key: config-file
            path: pd.toml
          name: basic-pd
        name: config
      - configMap:
          defaultMode: 420
          items:
          - key: startup-script
            path: pd_start_script.sh
          name: basic-pd
        name: startup-script
  updateStrategy:
    rollingUpdate:
      partition: 3
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: pd
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem